### ISSUE TITLE
Add proper description to README.md

### ISSUE THREAD

**Issue by goodmanslaugh** [goodmanslaugh/sidejourney#1]
Add proper description to readme file
- [ ] Include Project Logo
- [ ] Include Name
- [ ] Include Description

**Comment by abhishekpatil4** [comment]
Assign me this task, will get it done in no time. I'm a full-stack developer

**Comment by goodmanslaugh** [comment]
Done!

**Comment by prashantpadhy** [comment]
assign me this task

**Comment by prashantpadhy** [comment]
i am a mern stack developer

**Comment by goodmanslaugh** [comment]
@prashantpadhy please make a PR! There is no need for assignment.

**Comment by goodmanslaugh** [comment]
Fixed by #24

**Comment by abhishekpatil4** [comment]
@goodmanslaugh Please review my pull request
