### ISSUE TITLE
Add Github logo with project repo hyperlink at the top right of the website

### ISSUE THREAD

**Issue by goodmanslaugh** [goodmanslaugh/sidejourney#17]
- [ ] Add Github logo with project repo hyperlink at the top right of the website

<div align="center">
<img src="https://user-images.githubusercontent.com/115019431/194047083-b641615a-53a1-4a48-b2e0-20a0b06eb91a.png">
</div>

**Comment by RachitGarg-12** [comment]
Hey , I would like to contribute on this issue.

**Comment by goodmanslaugh** [comment]
Sure @RachitGarg-12, Please make a PR!

**Comment by goodmanslaugh** [comment]
Fixed by #25
