### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by goodmanslaugh** [goodmanslaugh/sidejourney#19]
- [ ] It appears that there is a need for CONTRIBUTING.md for newcomers.

**Comment by goodmanslaugh** [comment]
Sure @hfr58gb, make a PR!

**Comment by prashantpadhy** [comment]
done. plz check the pr

**Comment by hfr58gb** [comment]
Done assigned task, check PR
 thanks @goodmanslaugh

**Comment by goodmanslaugh** [comment]
@prashantpadhy thanks for your interest but this issue is already resolved. Please check #30

**Comment by goodmanslaugh** [comment]
Thanks for contributing @hfr58gb! :rocket:

**Comment by prashantpadhy** [comment]
i solved before him sir

**Comment by goodmanslaugh** [comment]
You have submitted a blank file and that was the main reason for not merging your PR. No worries there are plenty of issues out there, if not you can create one and make a PR @prashantpadhy
