### ISSUE TITLE
Add CODE-OF-CONDUCT.md

### ISSUE THREAD

**Issue by goodmanslaugh** [goodmanslaugh/sidejourney#21]
- [ ] Add CODE-OF-CONDUCT.md to the project

**Comment by Marcresi** [comment]
hey @goodmanslaugh , I would like to work on this.
Where can I find the code of conduct??

**Comment by goodmanslaugh** [comment]
Sure @Marcresi, make a PR!

**Comment by prashantpadhy** [comment]
done please merge pr
