### ISSUE TITLE
Add fetch API to the website

### ISSUE THREAD

**Issue by goodmanslaugh** [goodmanslaugh/sidejourney#3]
- [ ] Add javascript's fetch API to the website

**Comment by abhishekpatil4** [comment]
@goodmanslaugh Assign me this task, will get it done in no time. I'm a full-stack developer

**Comment by goodmanslaugh** [comment]
@abhishekpatil4 Thanks for your interest but this has been resolved. See #16  for more details! 

Tip: Don't ask for assignment. Just check if there exists a PR, if not create a patch and make a PR! :+1:
