### ISSUE TITLE
Add a centered form into the HTML page 

### ISSUE THREAD

**Issue by goodmanslaugh** [goodmanslaugh/sidejourney#9]
- Add a beautiful centered form using bulma css which takes username `text` as input

- Form layout should be centered vertically and horizontally

- Form method must be set to POST

- Form action must be set to `/`

- Mention this issue number in your PRs title

**Comment by B1TSH3LL** [comment]
i would like to work on it please assign it to me

**Comment by goodmanslaugh** [comment]
Done!

**Comment by B1TSH3LL** [comment]
i had created a PT please check i have added the Sign up form

**Comment by goodmanslaugh** [comment]
This isn't a signup form. Its a username search form

It has only one text input field

**Comment by B1TSH3LL** [comment]
please check it once again i had made all the changes

**Comment by B1TSH3LL** [comment]
please add the lables hacktoberfest , hacktoberfest2022 , hacktoberfest-accepted 💯 in the Closed PR else it will not count.

**Comment by goodmanslaugh** [comment]
Done!
